### ISSUE TITLE
Does not compile.

### ISSUE THREAD

**Issue by romanrm** [gawen947/imlib2-webp#1]
Hello,

```
# make
cc -Wp,-MMD,loader_webp.d -c -std=c99 -O2  -fPIC -Wall -ggdb -o loader_webp.o loader_webp.c
loader_webp.c:40:25: fatal error: webp/decode.h: No such file or directory
 #include <webp/decode.h>
                         ^
compilation terminated.
makefile:26: recipe for target 'loader_webp.o' failed
make: *** [loader_webp.o] Error 1
```

I suppose I need to get some webp sources/headers and copy them into the webp/ directory? Sure no problem I can probably figure this out. But the current README makes no mention or explanation whatsoever of this dependency -- perhaps something that could be improved.

**Comment by gawen947** [comment]
You have to install WebP headers. This is generally the libwebp-dev package on most distributions.
Agreed this was not listed in the dependencies. I will merge your patch. Thanks!
