### ISSUE TITLE
webp animation is not supported

### ISSUE THREAD

**Issue by zbutfly** [gawen947/imlib2-webp#3]
render webp with imlib2-webp through feh.

static webp works well, but animation could not be rendered.

sample: https://drive.google.com/file/d/1YgRDEc9UbeC5rXUrMfjp6JI_K4Fi6EDW/view?usp=sharing

**Comment by sgon00** [comment]
Even if this is closed, the animation still does not work. Only support displaying the first frame..

**Comment by gawen947** [comment]
Unfortunately imlib2 does not support animation :(
