### ISSUE TITLE
I just installed this on Ubuntu 18.04 (which is Debian-based). This check in the `Makefile` failed:

### ISSUE THREAD

**Issue by gawen947** [gawen947/imlib2-webp#7]
I just installed this on Ubuntu 18.04 (which is Debian-based). This check in the `Makefile` failed:

```
ifneq ($(.SHELLSTATUS),0)
$(error cannot guess imlib2 version)
endif
```

(it depends on make being at least 4.2 and Ubuntu 18.04 still has make 4.1)
so I took it out, and after `make` and `sudo make install`, my `feh` now loads .webp images. Thanks a bunch!

It would be nice if someone did a PPA for Debian/Ubuntu.

_Originally posted by @reinierpost in https://github.com/gawen947/imlib2-webp/issues/6#issuecomment-749242984_

**Comment by gawen947** [comment]
(re-opened here to avoid mixing different issues)

We have to check the version manually because some symbols exist only in newer version of imlib2, and they do not have macros in the include.

Could you try replacing in the Makefile:
```
ifneq ($(.SHELLSTATUS),0)
$(error cannot guess imlib2 version)
endif
```
with:
```
imlib2_version = $(shell ./imlib2-version.sh)
ifeq ($(imlib2_version), "")
$(error cannot guess imlib2 version)
endif
CFLAGS += $(imlib2_version)
```
and tell me if it works on Ubuntu 18.04?

For a Debian package and PPA, I don't use Debian personally, so I won't do it, but it would be very welcome. If someone wants to create a Debian package, or for any other distribution, I would look into pull-requests and could merge the debian folder and also update the README with appropriate references.

**Comment by hallzy** [comment]
I'm not the original person, but I am running 18.04 and this works for me, thanks

**Comment by gawen947** [comment]
Thanks! The fix has been merged.
